[CmdletBinding()]
param(
    [string]$MilvusDataDirectory = "D:/001-agent/milvus"
)

$ErrorActionPreference = "Stop"

function New-HexSecret {
    param([int]$Bytes = 24)
    $buffer = [byte[]]::new($Bytes)
    $generator = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $generator.GetBytes($buffer)
    }
    finally {
        $generator.Dispose()
    }
    return ([BitConverter]::ToString($buffer)).Replace('-', '')
}

$repositoryRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))
$configDirectory = Join-Path $repositoryRoot "config"
$target = Join-Path $configDirectory "deploy.local.env"
if (Test-Path -LiteralPath $target) {
    throw "config/deploy.local.env already exists; refusing to overwrite secrets."
}

$resolvedDataDirectory = [IO.Path]::GetFullPath($MilvusDataDirectory).TrimEnd([char[]]'\/')
$protectedLegacyDirectory = [IO.Path]::GetFullPath('D:/milvus').TrimEnd([char[]]'\/')
if (-not $resolvedDataDirectory.StartsWith('D:\', [StringComparison]::OrdinalIgnoreCase)) {
    throw "Milvus data must be stored on drive D."
}
if ($resolvedDataDirectory.Equals($protectedLegacyDirectory, [StringComparison]::OrdinalIgnoreCase)) {
    throw "Refusing to reuse protected legacy directory D:/milvus."
}

$postgresPassword = "PgA1" + (New-HexSecret 20)
$milvusPassword = "MvA1!" + (New-HexSecret 20)
$minioPassword = "MnA1!" + (New-HexSecret 20)
$internalToken = New-HexSecret 32
$portableDataDirectory = $resolvedDataDirectory.Replace('\', '/')

$lines = @(
    "# Generated by deploy/new-local-env.ps1. Git ignored; never commit or share.",
    "POSTGRES_DB=agent_workbench",
    "POSTGRES_USER=workbench",
    "POSTGRES_PASSWORD=$postgresPassword",
    "POSTGRES_BIND_ADDRESS=127.0.0.1",
    "POSTGRES_HOST_PORT=15432",
    "POSTGRES_VOLUME_NAME=001-agent-live-postgres-v1",
    "WORKBENCH_DATABASE_URL=postgresql://workbench:$postgresPassword@postgres:5432/agent_workbench",
    "WORKBENCH_DATABASE_SSL=false",
    "WORKBENCH_DATABASE_POOL_MAX=10",
    "",
    "SEARCH_AGENT_IMAGE=agent-workbench/search-agent:local",
    "SEARCH_AGENT_BIND_ADDRESS=127.0.0.1",
    "SEARCH_AGENT_HOST_PORT=8080",
    "SEARCH_AGENT_DATABASE_URL=postgresql://workbench:$postgresPassword@postgres:5432/agent_workbench",
    "SEARCH_AGENT_MILVUS_URI=http://milvus:19530",
    "WORKBENCH_INTERNAL_TOKEN=$internalToken",
    "",
    "WEB_IMAGE=agent-workbench/web:local",
    "WEB_BIND_ADDRESS=127.0.0.1",
    "WEB_PORT=3000",
    "",
    "MILVUS_DATA_DIRECTORY=$portableDataDirectory",
    "MILVUS_ROOT_PASSWORD=$milvusPassword",
    "MILVUS_MINIO_ROOT_USER=agentminio",
    "MILVUS_MINIO_ROOT_PASSWORD=$minioPassword",
    "",
    "AGENT_BACKEND_NETWORK=001-agent-live-backend",
    "AGENT_MILVUS_NETWORK=001-agent-live-milvus"
)

[IO.File]::WriteAllText($target, ($lines -join "`n") + "`n", [Text.UTF8Encoding]::new($false))
Write-Host "Generated Git-ignored config/deploy.local.env without printing secrets."
Write-Host "Milvus isolated data directory: $portableDataDirectory"
